[workspace]
members = ["squashfuse-rs", "examples/*"]

[workspace.dependencies]
backhand = "0.18.0"
fuser = "0.14.0"
libc = "0.2.155"
thiserror = "1.0.63"

squashfuse-rs = { version = "0.3.0", path = "squashfuse-rs" }